.PHONY: clean All

All:
	@echo "----------Building project:[ StrongholdEngine - Debug ]----------"
	@"$(MAKE)" -f  "StrongholdEngine.mk"
clean:
	@echo "----------Cleaning project:[ StrongholdEngine - Debug ]----------"
	@"$(MAKE)" -f  "StrongholdEngine.mk" clean
